apiVersion: v1
kind: Service
metadata:
  name: {{ include "single-container-chart.fullname" . }}
  labels:
    {{- include "single-container-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
      name: grpc
  selector:
    app: product
    {{- include "single-container-chart.selectorLabels" . | nindent 4 }}
